name: LockiPrefixes
version: ${version}
main: de.locki.lockiprefixes.LockiPrefixesPlugin
api-version: "1.20"
description: LuckPerms prefix/suffix formatter for chat and leaderboards
authors: [Locki]
website: https://github.com/locki/lockiprefixes
softdepend: [LuckPerms, PlaceholderAPI]

commands:
  lockiprefixes:
    description: LockiPrefixes - Rank style manager
    usage: /lockiprefixes <menu|reload>
    aliases: [lpx]

permissions:
  lockiprefixes.reload:
    description: Allows reloading the plugin configuration
    default: op
  lockiprefixes.chatcolor:
    description: Allows using color codes in chat
    default: false
  lockiprefixes.notify:
    description: Receives notifications about missing dependencies
    default: op
  lockiprefixes.menu:
    description: Allows opening the Prefix Manager GUI
    default: true