name: LockiPrefixes
version: ${version}
main: de.locki.lockiprefixes.LockiPrefixesPlugin
description: LuckPerms prefix/suffix formatter for chat and leaderboards
authors: [Locki]
website: https://github.com/locki/lockiprefixes
depend: [LuckPerms]
softdepend: [PlaceholderAPI]

commands:
  lockiprefixes:
    description: LockiPrefixes — Rank Manager
    usage: /lockiprefixes <menu|reload>
    aliases: [lpx]

permissions:
  lockiprefixes.reload:
    description: Allows reloading the plugin configuration
    default: op
  lockiprefixes.chatcolor:
    description: Allows using color codes in chat
    default: false
  lockiprefixes.menu:
    description: Allows opening the Prefix Manager GUI
    default: true
